// 이펙트 종류 — 풀링/재생 시 enum 값으로 이펙트를 지정
public enum PoolObjectType
{
    ELECTRIC_HIT_EFFECT,
    ELECTRIC_PROJECTILE_EFFECT,
    ICE_EXPLOSION_EFFECT,
    STORM_EFFECT,
    FIRE_EXPLOSION_EFFECT,
    FIRE_BUFF_EFFECT,
    MOTION_TRAIL_OBJECT,
    FROZEN_SMOKE_EFFECT,
    HIT_STONE_EFFECT,
    ELF_MOUSE_SKILL_EFFECT,
    ELF_Q_SKILL_EFFECT,
    COMBAT_TEXT,
}
